### ISSUE TITLE
Alchemy API keys

### ISSUE THREAD

**Issue by jyap808** [knav-eth/CHIMP#1]
You should make your Alchemy API keys an ENV var.

https://github.com/knav-eth/CHIMP/blob/main/hardhat.config.ts#L42

https://github.com/knav-eth/CHIMP/blob/main/hardhat.config.ts#L51

Thanks for making this project Open Source

**Comment by knav-eth** [comment]
Thanks, I checked Infura keys before open sourcing this but forgot to check Alchemy. Updated now.
